### ISSUE TITLE
[Feature] - Create an API for our two forms extension and add them as dependencies

### ISSUE THREAD

**Issue by peterhnm** [Miragon/miranum-copilot#100]
- [x] Description created
- [ ] Reviewed by peer: @manuw99 
- [ ] Prioritised

# Description
The copilot need access to the JSON content created by our existing VS Code Extensions. For this we need to add an API like in [this example](https://github.com/peterhnm/vscode-mock-text-editor). Afterwards we can add the extensions as [dependencies](https://github.com/Miragon/miranum-copilot/blob/87ad393608e3a4e27ddf78d804efd3f438e946bc/package.json#L35) and call there API.

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] Add API to [Miranum Forms](https://github.com/Miragon/miranum-ide/blob/6b31a4ce4a9de60b33e7197f8673f3a9c8e3202f/apps/miranum-forms/src/main.ts)
- [ ] Add API to [Miranum Json Forms](https://github.com/Miragon/miranum-json-forms/blob/a900dfcc01ca7dbd0d19ddaba44bdc92fde20ad3/src/extension.ts)
- [ ] Add dependencies
- [ ] Test the API calls
```
