### ISSUE TITLE
[Feature] - Create preconfigured prompts

### ISSUE THREAD

**Issue by peterhnm** [Miragon/miranum-copilot#101]
- [ ] Description created
- [ ] Reviewed by peer: @MichaelWildermann 
- [ ] Prioritised

# Description
We want to provide preconfigured prompts for the user to:
* Generate Test Data
* Generate Forms
> ❗ Note: At least one of our two extensions must be able to display the generated forms.

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] Create prompt for generating test data
- [ ] Create prompt for generating a form based on existing data provided as JSON
- [ ] Research on the possibility to use images within/together with a prompt
- [ ] Create prompt for generating a form based on a image
- [ ] Implement the prompts
```
