### ISSUE TITLE
[Feature] - Create preconfigured prompts for generating forms based on existing data

### ISSUE THREAD

**Issue by peterhnm** [Miragon/miranum-copilot#102]
- [ ] Description created
- [ ] Reviewed by peer: <tag-person-here>
- [ ] Prioritised

# Description
For form generation, we want to provide preconfigured prompts. The form will be generated based on test data that will be provided as JSON. At least one of our two extensions must be able to display the generated forms.

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] Create prompt for [Miranum Forms](https://github.com/Miragon/miranum-ide/blob/6b31a4ce4a9de60b33e7197f8673f3a9c8e3202f/apps/miranum-forms/src/main.ts)
- [ ] Create prompt for [Miranum Json Forms](https://github.com/Miragon/miranum-json-forms/blob/a900dfcc01ca7dbd0d19ddaba44bdc92fde20ad3/src/extension.ts)
```
