### ISSUE TITLE
[Feature] - Create preconfigured prompts for generating forms based on an image

### ISSUE THREAD

**Issue by peterhnm** [Miragon/miranum-copilot#103]
- [ ] Description created
- [ ] Reviewed by peer: @MichaelWildermann 
- [ ] Prioritised

# Description
For form generation, we want to provide preconfigured prompts. The form will be generated based on an image. At least one of our two extensions must be able to display the generated form.

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] Research on how to use images within/together with an prompt
- [ ] Create prompt for [Miranum Forms](https://github.com/Miragon/miranum-ide/blob/6b31a4ce4a9de60b33e7197f8673f3a9c8e3202f/apps/miranum-forms/src/main.ts)
- [ ] Create prompt for [Miranum Json Forms](https://github.com/Miragon/miranum-json-forms/blob/a900dfcc01ca7dbd0d19ddaba44bdc92fde20ad3/src/extension.ts)
- [ ] Implement prompts
```
