### ISSUE TITLE
[Feature] - Create side panel

### ISSUE THREAD

**Issue by peterhnm** [Miragon/miranum-copilot#104]
- [x] Description created
- [x] Reviewed by peer: @manuw99 
- [x] Prioritised

# Description
The user can choose from pre-configured prompts. These prompts are listed in a side panel that can be opened and closed with a menu button.

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] Create Vue Component for Side Panel
- [ ] Create Vue Component for Category
```

**Comment by peterhnm** [comment]
@MichaelWildermann [here](https://github.com/Miragon/miranum-copilot/blob/8e6873770ded73c302a513eedc40a5d009bf6caf/src/web/app/css/vscode-theme-colors.css) is the link to the stylesheet with the vscode variables.
