### ISSUE TITLE
[Research] - Research and evaluate existing and similar plugins

### ISSUE THREAD

**Issue by peterhnm** [Miragon/miranum-copilot#11]
- [x] Description created
- [ ] Reviewed by peer: <tag-person-here>
- [ ] Prioritised

# Description
We want to know of similar plugins to get an idea of what is needed for our own plugin. We also want to evaluate these plugins on how they work.

## Sub-Tasks
```[tasklist]
### Tasks
- [ ] Search and collect similar plugins
- [ ] Evaluate the collected plugins
```
