### ISSUE TITLE
[Research] - Research on possibilities to communicate between plugins

### ISSUE THREAD

**Issue by peterhnm** [Miragon/miranum-copilot#12]
- [x] Description created
- [x] Reviewed by peer: <tag-person-here>
- [x] Prioritised

# Description
Our plugin have to communicate with our other [plugins](https://marketplace.visualstudio.com/search?term=miranum&target=VSCode&category=All%20categories&sortBy=Relevance) to send data between them. With this issue we want to find and discuss solutions to meet this requirement.

## Sub-Tasks
```[tasklist]
### Tasks
- [x] Search the [VS Code API](https://code.visualstudio.com/api/references/vscode-api) for possible solotions
- [x] Determine how we want to implement it
```

**Comment by peterhnm** [comment]
There are two ways to communicate between extensions:
* By using commands. One extension can invoke the commands of the other extension.
* By using extension APIs. I made an [example](https://github.com/peterhnm/vscode-mock-text-editor) for that.
