### ISSUE TITLE
[Feature] Define Prompt(s) for Process Documentation Creation

### ISSUE THREAD

**Issue by peterhnm** [Miragon/miranum-copilot#122]
- [x] Description created
- [x] Reviewed by peer: <tag-person-here>
- [x] Prioritised

# Description
Define prompts for generating the process documentation.
Use the templates.

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] Define prompt with Markdown as output
- [ ] Define prompt with JSON as output
```
