### ISSUE TITLE
[Feature] - Create documentation

### ISSUE THREAD

**Issue by peterhnm** [Miragon/miranum-copilot#141]
- [ ] Description created
- [ ] Reviewed by peer: <tag-person-here>
- [ ] Prioritised

# Description
Once we have defined the documentation templates and prompts, we need to use them to generate the documentation with ChatGPT and create the actual file.

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] Read templates
- [ ] Put the templates into the prompt and send it to ChatGPT
- [ ] Await the response and create a file with the output from ChatGPT
```
