### ISSUE TITLE
[Epic] - Create an MVP for our plugin

### ISSUE THREAD

**Issue by peterhnm** [Miragon/miranum-copilot#19]
- [x] Description created
- [x] Reviewed by peer: @MichaelWildermann 
- [x] Prioritised

# Description
Our MVP should be able to communicate with ChatGPT. The input and output for this is done via the web view of the copilot. Furthermore, the copilot must be able to fetch the necessary data (XML) from the Miranum Modeler.

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] https://github.com/FlowSquad/miranum-copilot/issues/20
- [ ] https://github.com/FlowSquad/miranum-copilot/issues/21
- [ ] https://github.com/FlowSquad/miranum-copilot/issues/22
```

# Acceptance
* The webview should be able to accept input and display the response from ChatGPT.
* The plugin should be able to get the XML from the Miranum Modeler
