### ISSUE TITLE
[Feature] - Connect ChatGPT to the plugin

### ISSUE THREAD

**Issue by peterhnm** [Miragon/miranum-copilot#21]
- [x] Description created
- [x] Reviewed by peer: @MichaelWildermann 
- [ ] Prioritised

# Description
This issue is to connect the Copilot to ChatGPT. For this we need a simple but secure way to store the API key.

## Sub-Tasks
```[tasklist]
### Tasks
- [ ] Request access to ChatGPT Api
- [ ] Swap the mocked API call with an actual one
- [ ] Enable the API key to be saved
```
