### ISSUE TITLE
[Feature] - Provide an API for the Miranum Modeler and use it within the Copilot

### ISSUE THREAD

**Issue by peterhnm** [Miragon/miranum-copilot#22]
- [x] Description created
- [x] Reviewed by peer: @MichaelWildermann 
- [x] Prioritised

# Description
To be able to query ChatGPT about the BPMN model currently being processed, we need access to the XML. Therefore, we need to provide an API for the [Miranum Modeler](https://github.com/FlowSquad/miranum-ide/tree/main/apps/miranum-modeler). Using the API we can create a command that copies the XML into the input field of our webview.
> *_Note:_* Use the insights from #12.

## Sub-Tasks
```[tasklist]
### Tasks
- [x] Provide the API
- [x] Register a command to copy the xml in the input field
```
