### ISSUE TITLE
[Epic] - Create basic VS Code Plugin

### ISSUE THREAD

**Issue by peterhnm** [Miragon/miranum-copilot#5]
- [x] Description created
- [ ] Reviewed by peer: <tag-person-here>
- [ ] Prioritised

# Description
This epic will lay the foundation for our VS Code plugin. This means to create the node project and research on existing plugins.

## Sub-Tasks
```[tasklist]
### Tasks
- [ ] https://github.com/FlowSquad/miranum-copilot/issues/11
- [ ] https://github.com/FlowSquad/miranum-copilot/issues/12
- [ ] https://github.com/FlowSquad/miranum-copilot/issues/13
- [ ] https://github.com/FlowSquad/miranum-copilot/issues/14
```

## Stakeholder
@peterhnm 

# Acceptance
* We know of similar plugins and tried them out
* We know how we can send data between two plugins
* A basic setup for VS Code Plugins exist

**Comment by Hafflgav** [comment]
This epic sounds good to me and seems like a good way to start off this project. Even when personas are not defined yet. 
Especially since this is the ground work and nothing use-case specific. 👍 

@peterhnm can you create issues for the sub-tasks and reference them in here as well?
