### ISSUE TITLE
[Research] Analyse whether existing ChatGPT Plugins can leverage an advantage

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum-copilot#71]
- [x] Description created
- [x] Reviewed by peer: @manuw99 
- [ ] Prioritised

# Description
In this research story we want to find out whether already existing ChatGPT can improve the quality of answers Miranum Copilot is giving.

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] <your-issue-here>
- [ ] https://github.com/Miragon/miranum-copilot/issues/91
```

**Comment by Hafflgav** [comment]
@manuw99, can you take a look on this research story and refine it?
