### ISSUE TITLE
[Feature] - Add loading animation to the prompt area

### ISSUE THREAD

**Issue by manuw99** [Miragon/miranum-copilot#90]
- [x] Description created
- [x] Reviewed by peer: <tag-person-here>
- [x] Prioritised

# Description
We want to improve our UI for a better user experience. Therefore some additional features and quality of life upgrades are to be added to the existing UI.

- A loading animation would be helpful to see if the application is still in the process of loading the prompt. (Especially on longer, more complex requests to the AI).

## Sub-Tasks
 
```[tasklist]
### Tasks
- [x] Add loading behaviour
- [ ] Search for / create the animation
```
