### ISSUE TITLE
[Feature] - Search for helpful existing plugins

### ISSUE THREAD

**Issue by manuw99** [Miragon/miranum-copilot#91]
- [ ] Description created
- [ ] Reviewed by peer: <tag-person-here>
- [ ] Prioritised

# Description
We want to leverage ChatGPT Plugins to improve our application. For this we first have to identify helpful plugins and compare them.

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] Identify potentially helpful plugins
- [ ] Compare and evaluate the findings
```
