### ISSUE TITLE
[Feature] - Add pre-defined prompts to the prompt area

### ISSUE THREAD

**Issue by manuw99** [Miragon/miranum-copilot#92]
- [x] Description created
- [x] Reviewed by peer: @peterhnm 
- [x] Prioritised

# Description
We want to improve our UI for a better user experience. Therefore some additional features and quality of life upgrades are to be added to the existing UI.

- Pre-defined prompts can be useful for new users as suggestions or also helpful for frequent users as shortcuts for their requests.

## Sub-Tasks
 
```[tasklist]
### Tasks
- [x] Read JSON file with pre-defined prompts
- [x] Send prompts to the frontend on initialization
- [x] Add a function to display the user-clicked prompt in the "prompt-field"
- [ ] Add a user config with link to the JSON Schema file for customization
```
