### ISSUE TITLE
[Feature] - Collect and categorize pre-defined prompts

### ISSUE THREAD

**Issue by manuw99** [Miragon/miranum-copilot#93]
- [x] Description created
- [x] Reviewed by peer: <tag-person-here>
- [x] Prioritised

# Description

We're collecting ideas for pre-defined prompts and then attempting to categorize them in order to better fit the planned drop-down menu style.

Predefined queries could be:
* Generate a process documentation
* What does this process do
* Generate forms for user tasks in the process

## Sub-Tasks
 
```[tasklist]
### Tasks
- [x] Create a JSON file with examples of pre-configured prompts
- [x] Test and further improve prompts in ChatGPT conversation
```

**Comment by manuw99** [comment]
Collection of prompts (put into fitting categories):

General Questions:
- What is business process modeling, and why is it important for organizations?
- What does this process do?
- What are common mistakes to avoid when creating BPMN diagrams?
- Can you create a basic bpmn diagram for the following process: 


BPMN Help:
- How can I represent decision points in a BPMN Diagram?
- What's the best way to depict parallel activities in BPMN?
- Explain the different types of gateways in BPMN and when to use each.
- Can you provide examples of inclusive and exclusive gateways?
- Can you help me understand when to use manual tasks and automated tasks?
- What are some best practices for naming tasks and activities in BPMN?


Specific tasks:
- Give me ideas on how to represent user tasks in BPMN.
- How do I model a service task that interacts with an external system?
- How can I show that an error occurred during a process step?
- Are there ways to improve this model?


Forms:
- What benefits does the creation and usage of forms have?
- Generate a form for user tasks in the process.
- Include a brief description for each form field in the form.
- How can I optimize this form?
- Design a visually appealing form layout for a process.


Process Documentation:
- Generate a process documentation as text
- Generate a process documentation as a .json file 
- Generate a process documentation as a .md
- Generate a process documentation as a .json file using the file process.json as a template
- Generate a process documentation as a .json file using the file process.schema.json as a template
- Generate a process documentation as a .md using the file process.md as a template

**Comment by manuw99** [comment]
Added JSON file containing the prompts to resources folder #282ead8

**Comment by manuw99** [comment]
I've researched guidelines for creating well written prompts (keyword prompt engineering) and tried to set up a framework for prompts in the BPM domain.

### Helpful sources:

- Prompt Engineering Tutorial – Master ChatGPT and LLM Responses
https://www.youtube.com/watch?v=_ZvnD73m40o&pp=ygUacHJvbXB0IGVuZ2luZWVyaW5nIGNoYXRncHQ%3D

- Master the Perfect ChatGPT Prompt Formula (in just 8 minutes)! 
https://www.youtube.com/watch?v=jC4v5AS4RIM

- Master Prompt Engineering: Prompt Recipes - A Framework for Reusable AI Prompts
https://www.promptengineering.org/master-prompt-engineering-prompt-recipes/

- Elements of a Prompt
https://www.promptingguide.ai/introduction/elements

- What Are Large Language Model (LLM) Agents and Autonomous Agents
https://www.promptengineering.org/what-are-large-language-model-llm-agents/

- Asking ChatGPT about well written prompts directly




### For our background the following criteria are most relevant:

**1. Task:** The task that the AI is asked to perform.
**2. Instructions:** Further instructions if needed (Output, structure, Do's and Don'ts, Examples) 
**3. Input:** (Data) Input or the question.
**4. Context:** Perspective, goal, target audience
**6. (Role/persona):** Should the AI take on a role or persona? E.g. "In the role of a BPM-Specialist..."
**7. (Tone):** As ChatGPT itself said: 
"_Be Polite and Respectful:
Maintain a polite and respectful tone throughout your conversation. Remember that the chatbot is a digital entity, but it's always good practice to be courteous._"
The prompt can be written in a certain tone which will in hindsight influence the tone of the answer. In our case we should stick to a neutral, professional tone.
**9. (Type or format of output):** The output can be received in a specific format (e.g. JSON, .md) or type.
